#!/usr/bin/env node
/* SRE Track — build locale files from translated JSON.

   Reads  i18n/target/<locale>/<domain>.json
   Writes content/<locale>/wN.js, i18n/ui.<locale>.js, i18n/dg.<locale>.js

   Content files are generated from the English object with only strings
   substituted, so a locale cannot drift structurally: answer indices, question
   types, health deltas and node ids are carried over, never retyped.

   Usage: node tools/import.js --locale de [--domain w1|ui|dg|all]
*/
const fs = require('fs');
const path = require('path');
const { ROOT, readManifest, loadOwnWorlds, walkWorld, run } = require('./lib');
const { restore } = require('./protect');

const args = process.argv.slice(2);
const argOf = n => { const i = args.indexOf(n); return i >= 0 ? args[i + 1] : null; };
const locale = argOf('--locale');
const only = argOf('--domain') || 'all';
if (!locale) { console.error('usage: node tools/import.js --locale <code> [--domain <d>]'); process.exit(2); }

const { locales, fallback } = readManifest();
if (!locales[locale]) { console.error('locale not in i18n/manifest.js: ' + locale); process.exit(2); }
if (locale === fallback) { console.error('refusing to overwrite the source locale'); process.exit(2); }

const SRC = path.join(ROOT, 'i18n/source');
const TGT = path.join(ROOT, 'i18n/target', locale);
const problems = [];
const want = d => only === 'all' || only === d;

function readTarget(domain) {
  const p = path.join(TGT, domain + '.json');
  if (!fs.existsSync(p)) return null;
  return JSON.parse(fs.readFileSync(p, 'utf8'));
}
function readParts(domain) {
  const p = path.join(SRC, domain + '.parts.json');
  return fs.existsSync(p) ? JSON.parse(fs.readFileSync(p, 'utf8')) : {};
}

/* Restores %N% markers and reports any that went missing in translation. */
function resolve(domain, target, parts) {
  const out = {};
  Object.keys(target).forEach(k => {
    const raw = target[k];
    if (typeof raw !== 'string') { problems.push(domain + ' ' + k + ': value is not a string'); return; }
    if (parts[k]) {
      const r = restore(raw, parts[k]);
      r.problems.forEach(p => problems.push(domain + ' ' + k + ': ' + p));
      out[k] = r.text;
    } else {
      if (/%\d+%/.test(raw)) problems.push(domain + ' ' + k + ': has %N% markers but the source had none');
      out[k] = raw;
    }
  });
  return out;
}

const header = (what) => '/* SRE Track — ' + what + ': ' + locale + '\n' +
  '   Generated by tools/import.js from i18n/target/' + locale + '/. Do not hand-edit:\n' +
  '   edit the JSON and re-run the importer, so structure stays tied to English. */\n';

let wrote = 0;

// ---- UI ----
if (want('ui')) {
  const target = readTarget('ui');
  if (target) {
    const flat = resolve('ui', target, readParts('ui'));
    const cat = {};
    Object.keys(flat).forEach(k => {
      const hash = k.indexOf('#');
      if (hash === -1) { cat[k] = flat[k]; return; }
      const base = k.slice(0, hash), form = k.slice(hash + 1);
      cat[base] = cat[base] && typeof cat[base] === 'object' ? cat[base] : {};
      cat[base][form] = flat[k];
    });
    fs.writeFileSync(path.join(ROOT, 'i18n/ui.' + locale + '.js'),
      header('UI string catalog') + 'window.SRE_UI_ALL = window.SRE_UI_ALL || {};\nwindow.SRE_UI_ALL[' +
      JSON.stringify(locale) + '] = ' + JSON.stringify(cat, null, 2) + ';\n');
    console.log('wrote i18n/ui.' + locale + '.js  (' + Object.keys(cat).length + ' keys)');
    wrote++;
  }
}

// ---- diagram labels ----
if (want('dg')) {
  const target = readTarget('dg');
  if (target) {
    const flat = resolve('dg', target, readParts('dg'));
    fs.writeFileSync(path.join(ROOT, 'i18n/dg.' + locale + '.js'),
      header('diagram label catalog') + 'window.SRE_DG_ALL = window.SRE_DG_ALL || {};\nwindow.SRE_DG_ALL[' +
      JSON.stringify(locale) + '] = ' + JSON.stringify(flat, null, 2) + ';\n');
    console.log('wrote i18n/dg.' + locale + '.js  (' + Object.keys(flat).length + ' labels)');
    wrote++;
  }
}

// ---- content ----
const enWorlds = loadOwnWorlds(fallback);
fs.mkdirSync(path.join(ROOT, 'content', locale), { recursive: true });
enWorlds.forEach((world, wi) => {
  const domain = 'w' + (wi + 1);
  if (!want(domain)) return;
  const target = readTarget(domain);
  if (!target) return;
  const flat = resolve(domain, target, readParts(domain));
  const missing = [];
  walkWorld(world, wi, (key, value, set) => {
    if (flat[key] === undefined) { missing.push(key); return; }
    set(flat[key]);
  });
  if (missing.length) problems.push(domain + ': ' + missing.length + ' key(s) absent from the target, e.g. ' + missing.slice(0, 3).join(', '));
  fs.writeFileSync(path.join(ROOT, 'content', locale, domain + '.js'),
    header('world ' + (wi + 1) + ' content') +
    'window.SRE_WORLDS = window.SRE_WORLDS || [];\nwindow.SRE_WORLDS.push(' + JSON.stringify(world, null, 2) + ');\n');
  console.log('wrote content/' + locale + '/' + domain + '.js');
  wrote++;
});

if (!wrote) { console.error('nothing to import: no JSON found under i18n/target/' + locale + '/'); process.exit(1); }
if (problems.length) {
  console.error('\n' + problems.length + ' problem(s):');
  problems.forEach(p => console.error('  - ' + p));
  process.exit(1);
}
console.log('\nimport clean. Now run: node tools/check-locales.js && node tools/check-svg-fit.js --locale ' + locale);
